POST http://localhost:3030/usuario
Content-Type: application/json

{
    "nome": "Marcel",
    "telefone": "67996029831",
    "dataNascimento": "2002-04-10T00:00:00",
    "cpf": "99999999999",
    "email": "marcel10042002@gmail.com",
    "senha": "1092813asd",
    "uf": "MS",
    "cidade": "campo grande",
    "tipoSanguineo": "A+"
}